### ISSUE TITLE
Upgrade Decidim to version 0.14.3

### ISSUE THREAD

**Issue by xredo** [diputacioBCN/decidim-diba#28]
The current installed version is 0.8.3. The process might need to be done in several steps as 0.14 includes some changes that break previous migrations.

## Tasks:

- [ ] Upgrade Ruby version
- [ ] Upgrade Decidim dependencies
- [ ] Apply changes mentioned in the upgrade notes
- [ ] Check if there is a better supported solution for the `decidim-age_action_authorization`. 
- [ ] Check decidim-census behaviour
- [ ] Check decidim-diba_census_api behaviour
- [ ] Check decidim-ldap behaviour. Some layouts are being overriden
 
## Upgrade Notes

- https://github.com/decidim/decidim/blob/0.9-stable/CHANGELOG.md#v090-2018-2-5
- https://github.com/decidim/decidim/blob/0.11-stable/CHANGELOG.md#0111
- https://github.com/decidim/decidim/blob/0.12-stable/CHANGELOG.md#0120
- https://github.com/decidim/decidim/blob/0.13-stable/CHANGELOG.md#0130
- https://github.com/decidim/decidim/blob/0.14-stable/CHANGELOG.md#0141
