### ISSUE TITLE
Install new modules

### ISSUE THREAD

**Issue by xredo** [diputacioBCN/decidim-diba#34]
## Description

We need to add the decidim-initiatives and the decidim-consultations gems to the decidim-diba installation. They are 2 standalone modules that can be configured on the main repo.

We have already checked that don't seem incompatible with current customizations so it should be an easy integration.

**Estimated completion time:** 2h

## Tasks

- [ ] Install Decidim Initiatives module
- [ ] Install Decidim Consultations module
- [ ] Test for incompatibilities with current development

## Relevant links

- https://github.com/decidim/decidim/tree/master/decidim-consultations
- https://github.com/decidim/decidim/tree/master/decidim-initiatives
