### ISSUE TITLE
New AuthorizationHandler to check the census from an excel file

### ISSUE THREAD

**Issue by xredo** [diputacioBCN/decidim-diba#7]
### Description

A new AuthorizationHandler will be created to allow new users to be validated against a census that will be uploaded from an excel file. The AuthorizationHandler will accept the citizen minimum age as a configuration parameter. If the user doesn't meet the age requirement configured in the parameter it won't be authorised. 

The excel file will have a CSV format and it will contain the following data for every user: 

- ID document
- Birth Date

The excel file will be uploaded from the Admin Panel of every organisation. Only users with the admin role will be able to upload the excel file. We will display if there is any excel file loaded and if there is one, the date when it was loaded and the number of citizens loaded to the organisation.

### Tasks

- [x] Add a new section in the Decidim Admin Panel to upload a new Excel file for an organisation.
- [x] Display the date when the excel was uploaded for the last time and the number of citizens in the census for the organization.
- [x] Create a new AuthorizationHandler that will use the data uploaded from the excel file.
- [x] The AuthorizationHandler will be configurable with a minimum user age required to authorise the user.
- [x] Attach a sample excel file in xlsx format to the issue.

### Technical discussion

We need to analyse if creating an engine is the best way to encapsulate the code that we will be writing. I suggest implementing first a version overriding the Decidim behaviours in the project itself and then determine if the added core is complex enough to be created as a separate extension.

### Resources

- Creating a new authorization handler: https://github.com/decidim/decidim/blob/master/docs/getting_started.md#creating-an-authorization-handler
- Authorization Handler base class with documentation: https://github.com/decidim/decidim/blob/master/decidim-core/app/services/decidim/authorization_handler.rb
- Decidim Vilanova MarsBased implementation of an Authorization Handler: https://github.com/vilanovailageltru/decidim-vilanova/pull/34/files
- Creating an engine in Decidim: https://github.com/decidim/decidim/blob/master/docs/how_to_create_a_plugin.md

**Comment by xredo** [comment]
There are new requirements regarding the upload of the Excel files: Remove census for an organization and incremental updates.

### Incremental updates

When a new CSC is uploaded we won't remove any existing record. We will load the new ones incrementally.

### Remove Census

A new button in the Census admin view is required to remove all the Census that has been loaded for an organization.

**Comment by danigb** [comment]
Additional tasks:

- [x] When importing, normalize all document numbers by removing all non-letter or number characters, and converting to upper case
- [ ] When querying (AuthorizationHandler), apply the same document number normalization
- [x] Import should merge instead of replacing data (and remove duplicates: last wins)
- [ ] Add a button to the UI to remove all census data
- [ ] Check performance with 200k CSV file
