### ISSUE TITLE
AuthorizationHandler that check users against the Diputacio Census API

### ISSUE THREAD

**Issue by xredo** [diputacioBCN/decidim-diba#8]
### Description

A new AuthorizationHandler will be created to allow new users to be validated against a census provided by an API.

The AuthorizationHandler will accept the citizen minimum age as a configuration parameter. If the user doesn't meet the age requirement configured in the parameter it won't be authorised. 

The AuthorizationHandler will also accept the INE (municipality identifier code) param. All requests to check if a user belongs to a census will be filtered by the INE.

The AuthorizationHandler will request the following data to the user:

- ID document number
- ID document number kind
- Birthday

### API specification

The API is a XML API. The API call to retrieve the results from the Census requires an XML to be sent inside the request with the following format:

```xml
<e>
	<ope>
		<apl>PAD</apl>
		<tobj>HAB</tobj>
		<cmd>DATOSHABITANTES</cmd>
		<ver>2.0</ver>
	</ope>
	<sec>
		<cli><!--ENV_VARIABLE--></cli>
		<org><!--ENV_VARIABLE--></org>
		<ent><!--NIE code of the municipaly--></ent>
		<usu><!--ENV_VARIABLE--></usu>
		<pwd><!--ENV_VARIABLE--></pwd>
	</sec>
	<par>
		<codigoTipoDocumento>1</codigoTipoDocumento>
		<documento>123456789B</documento>
		<fechaNacimiento>07/03/2014</fechaNacimiento>
                <busquedaExacta>0</busquedaExacta>
	</par>
</e>
```

codigoTipoDocumento accepts the following values:

- 1 - NIF
- 2 - Passport
- 3 - Residence card
- 4 - DNI 

> ⚠️ The response from the API is still pending definition. ⚠️

### Tasks

- [ ] Build a service to interact with the Diputacio Census API
- [ ] Make the Census API host and credentials configurable via env variables
- [ ] Create a new AuthorizationHandler that will use the Census API to authorise users
- [ ] The AuthorizationHandler will be configurable with a minimum user age required to authorise the user.
- [ ] The AuthorizationHandler will be configurable with the INE (municipality identifier code)

### Technical discussion

We need to analyse if creating an engine is the best way to encapsulate the code that we will be writing. I suggest implementing first a version overriding the Decidim behaviours in the project itself and then determine if the added core is complex enough to be created as a separate extension.

### Resources

- Creating a new authorization handler: https://github.com/decidim/decidim/blob/master/docs/getting_started.md#creating-an-authorization-handler
- Authorization Handler base class with documentation: https://github.com/decidim/decidim/blob/master/decidim-core/app/services/decidim/authorization_handler.rb
- Decidim Vilanova MarsBased implementation of an Authorization Handler: https://github.com/vilanovailageltru/decidim-vilanova/pull/34/files
- Creating an engine in Decidim: https://github.com/decidim/decidim/blob/master/docs/how_to_create_a_plugin.md

**Comment by xredo** [comment]
There is one additional requirement.

The Municipaly (INE) param will be configured for every organization. The webservice username and password will be configurable also at a organization level.

**Comment by danigb** [comment]
Aditional tasks:

- [ ] Add configuration field to Decidim::Organization (census_api_ine, census_api_username, census_api_password)
- [ ] Add admin pages to change the configuration of the current organization
- [ ] Show instructions if the DibaCensusApiAuthorizationHandler is not installed
- [ ] Use the AuthorizeWithAge from the decidim-census package instead of copy & paste
- [ ] Send requests against the actual API (more ducoumentation is required)
